# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  imageName: 'activityreservation'

steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: Dockerfile
    
    