# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  imageName: 'qs.web.api'

steps:

      - task: Docker@2
        inputs:
          containerRegistry: 'qs_regisitry'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: 'qs_regisitry'
          repository: '$(imageName)'
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        inputs:
          containerRegistry: 'qs_regisitry'
          repository: '$(Build.Repository.Name)'
          command: 'push'
    