# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  imageName: 'activityreservation'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: QSPool
    steps:
    - script: |
        docker build -f Dockerfile -t $(imageName) .
        docker login -u $(dockerId) -p $(pswd)
        docker push $(imageName)