# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  
steps:
  - task: CmdLine@2
    inputs:
      script: 'docker build -t qs.web.api:latest .'
  - task: CmdLine@2
    inputs:
      script: |
        docker login -u=zhangyaxing521@qq.com -p qazplm,./$ registry.cn-hangzhou.aliyuncs.com
        docker tag qs.web.api registry.cn-hangzhou.aliyuncs.com/qs315/qsres:latest
        docker push registry.cn-hangzhou.aliyuncs.com/qs315/qsres:latest