# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'qs_regisitry'
        repository: 'qs.web'
        command: 'build'
        Dockerfile: '**/Dockerfile'