# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'
  imageName: 'activityreservation'

pool:
    vmImage: 'ubuntu-1604' # set to windows-latest or another Windows vmImage for Windows builds

steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(imageName)
            command: build
            Dockerfile: Dockerfile
    
    