# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  
steps:
  - task: CmdLine@2
    inputs:
      script: 'docker build -t qs.web.api:latest .'