# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: QSPool
    steps:
    - task: Docker@2
      inputs:
        repository: 'qs.web'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)'