# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: 'QSPool'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'qs_regisitry'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'qs_regisitry'
        repository: 'qs.core.api'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'